# Site settings
title: Deev Interaction on the web
email: contact@deev-interaction.com
description: News and projects from Deev Interaction

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://legras.github.io" # the base hostname & protocol for your site

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/DeevInteraction
  - title: github
    url: http://github.com/legras

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
